#!/usr/bin/env bash
# Applies a validated agent patch on a new branch and opens a DRAFT pull request.
# Runs in a job that has write permissions but no sandbox and no agent.
#
# Inputs (environment): PATCH_FILE, ALLOWED_PREFIXES, TITLE_PREFIX, BASE_BRANCH, GH_TOKEN,
# and optionally AGENT_LOG. GITHUB_* variables come from Actions.
set -euo pipefail

: "${PATCH_FILE:?}" "${ALLOWED_PREFIXES:?}" "${BASE_BRANCH:?}" "${GH_TOKEN:?}"
TITLE_PREFIX="${TITLE_PREFIX:-}"
AGENT_LOG="${AGENT_LOG:-}"
run_id="${GITHUB_RUN_ID:-local}"
run_url="${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-owner/repo}/actions/runs/${run_id}"
branch="sbx-agent/run-${run_id}-${GITHUB_RUN_ATTEMPT:-1}"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "::group::Validate the patch"
files="$("${here}/validate-patch.sh" "${PATCH_FILE}" "${ALLOWED_PREFIXES}")"
echo "${files}"
echo "::endgroup::"

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -b "${branch}"
git apply --index --whitespace=nowarn "${PATCH_FILE}"

# Second check, on what is actually staged after the apply.
staged="$(git diff --cached --name-only | sort)"
if [[ "${staged}" != "$(printf '%s\n' "${files}" | sort)" ]]; then
  echo "::error::Staged files differ from the validated list" >&2
  exit 1
fi

git commit -q -m "Proposed change from sbx agent run ${run_id}" \
  -m "Generated by the Copilot agent in a Docker Sandbox: ${run_url}"
git push origin "${branch}"

body="$(mktemp)"
{
  echo "Proposed by the Copilot agent running in a Docker Sandbox. **Draft: needs human review.**"
  echo
  echo "Workflow run: ${run_url}"
  echo
  echo "Files changed (only paths under \`${ALLOWED_PREFIXES}\` are accepted):"
  echo
  while IFS= read -r f; do echo "- \`${f}\`"; done <<< "${files}"
  if [[ -n "${AGENT_LOG}" && -s "${AGENT_LOG}" ]]; then
    echo
    echo "<details><summary>End of the agent's output</summary>"
    echo
    echo '```text'
    # Agent output is untrusted: no backticks (fence breakout) and no @mentions.
    tail -c 4000 "${AGENT_LOG}" | tr -d '\r' | sed -e 's/`/'"'"'/g' -e 's/@/(at)/g'
    echo
    echo '```'
    echo "</details>"
  fi
} > "${body}"

gh pr create --draft \
  --base "${BASE_BRANCH}" \
  --head "${branch}" \
  --title "${TITLE_PREFIX}Proposed change from agent run #${GITHUB_RUN_NUMBER:-0}" \
  --body-file "${body}"
